#!/usr/bin/env python

import sys
import catsnap
from catsnap import Config
from catsnap.image import Image

def main():
    config = catsnap.Config()
    config.ensure_config_files_exist()
    bucket = config.bucket()
    image = Image.new_from_url(sys.argv[1])
    image.save(bucket)
    print image.url(bucket)

main()
